openapi: 3.0.1
info:
  title: AAFE Airports API
  description: Search airports by code or by name
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: airports-api
    description: Airports API
paths:
  /airports/{code}:
    get:
      tags:
        - airport-api
      operationId: getById
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Airport'
        '404':
          description: NotFound
  /airports:
    get:
      tags:
        - airport-api
      operationId: search
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            pattern: ^[a-zA-Z0-9]+$
        - name: page
          in: query
          description: Page number of the requested page. Defaults to first page, which is 0
          schema:
            type: integer
            format: int32
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Size of a page. Defaults to 100 items.
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 50
            default: 5
      responses:
        '200':
          description: Airports with comply with search string
          content:
            'application/json':
              schema:
                type: object
                required:
                  - page
                  - content
                properties:
                  page:
                    $ref: '#/components/schemas/Page'
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Airport'
        '400':
          description: BadRequest
components:
  schemas:
    Page:
      type: object
      title: Page
      required:
        - number
        - size
        - totalElements
        - totalPages
      properties:
        number:
          type: integer
          format: int32
          description: Current page of search result
          default: 0
        size:
          type: integer
          format: int32
          description: Current desired amount of items per result page.
          default: 100
        totalElements:
          type: integer
          format: int64
          description: Total amount of items meeting the search criteria.
          default: 0
        totalPages:
          type: integer
          format: int32
          description: Total amount of available pages compared to the given pageSize.
          default: 0
    Airport:
      required:
        - icao
        - name
      type: object
      properties:
        icao:
          type: string
        iata:
          type: string
        name:
          type: string
        location:
          $ref: '#/components/schemas/Location'
    Coordinates:
      required:
        - latitude
        - longitude
      type: object
      properties:
        latitude:
          $ref: '#/components/schemas/Latitude'
        longitude:
          $ref: '#/components/schemas/Longitude'
    Latitude:
      required:
        - degrees
        - direction
        - minutes
        - seconds
      type: object
      properties:
        degrees:
          type: integer
          format: int32
        minutes:
          type: integer
          format: int32
        seconds:
          type: integer
          format: int32
        direction:
          type: string
          enum:
            - 'N'
            - S
    Location:
      required:
        - city
        - coordinates
        - country
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        altitude:
          type: integer
          format: int32
    Longitude:
      required:
        - degrees
        - direction
        - minutes
        - seconds
      type: object
      properties:
        degrees:
          type: integer
          format: int32
        minutes:
          type: integer
          format: int32
        seconds:
          type: integer
          format: int32
        direction:
          type: string
          enum:
            - E
            - W
