# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    root: INFO
    web: INFO
    org:
      springframework:
        web: INFO
    com:
      aafe:
        fareengine:
          service: INFO
    springframework:
      cache: DEBUG

# Application Metadata
spring:
  application:
    name: aafe-fare-engine
    version: 1.0.0
  profiles:
    active: dev

airport:
  api:
    base-url: http://localhost:3000

# Fare Engine Configuration
fareengine:
  distance-method: haversine
#  distance-method: accurate
  distance-cost-per-km: 0.05
  stopover-cost: 25.00
  fixed-base-cost: 50.00
  tax-rate: 0.21
  service-charges:
    departure:
      "SIN,CFU,AMM,LIR,BOD,GDN,AMS,BRE": 50.00
      "IAH,PKX,LED,AAL": 30.00
      "SPC,SZG,SXM,ZAG,DAR,TBS": 20.00
    arrival:
      "CMN,OTP,TBS,SMI,BRI,IAD": 50.00
      "LIM,GLA,MAH,DAR,DUS,BOS,NCL,BRS,PSA,ZRH,EFL,FCO,AUS,ACC,SKG": 30.00
      "PMI,KLX,SFO,ATL,BSL,ALC,BLL,PRG,CTA,NCE,NUE,DPS,LPA,GYE,OSL": 20.00
    intermediate:
      "SOU,DBV,CTA,CAG,KRK,LHR,BCN,HAM,INV,IBZ,GDN,KTW,HRE,VCE,ABZ": 35.00
      "SZG,HAJ,CHQ,ORY,ACC,BKK,BHD": 25.00
      "WRO,RIX,TRF,BOG,ACE,PRG,KEF,MCO,BOJ,NBO,LIR,BGO,LBA": 15.00
  forbidden-starts:
    - BHD
    - LCA
    - HAJ
    - ACE
    - TPE
    - FLR
    - ATL
    - MUC
  forbidden-ends:
    - CAG
    - LYS
    - ATH
    - GYE
    - SMI
    - OLB
  served-stations:
    - AAL
    - AAR
    - ABZ
    - ACC
    - ACE
    - AES
    - AGP
    - ALC
    - AMM
    - AMS
    - ARN
    - ATH
    - ATL
    - AUA
    - AUH
    - AUS
    - BAH
    - BCN
    - BEG
    - BER
    - BEY
    - BGI
    - BGO
    - BHD
    - BHX
    - BIO
    - BKK
    - BLL
    - BLQ
    - BLR
    - BOD
    - BOG
    - BOJ
    - BOM
    - BON
    - BOS
    - BRE
    - BRI
    - BRS
    - BRU
    - BSL
    - BUD
    - CAG
    - CAN
    - CDG
    - CFU
    - CGK
    - CHQ
    - CMN
    - CPH
    - CPT
    - CTA
    - CTG
    - CUN
    - CUR
    - CWL
    - DAR
    - DBV
    - DEL
    - DMM
    - DPS
    - DRS
    - DTW
    - DUB
    - DUS
    - DXB
    - EBB
    - EDI
    - EFL
    - EZE
    - FAO
    - FCO
    - FLR
    - FNC
    - FRA
    - FUE
    - GDN
    - GIG
    - GLA
    - GOA
    - GOT
    - GRO
    - GRU
    - GRZ
    - GUA
    - GVA
    - GYE
    - HAJ
    - HAM
    - HEL
    - HER
    - HKG
    - HRE
    - HRG
    - HUY
    - IAD
    - IAH
    - IBZ
    - ICN
    - INN
    - INV
    - IST
    - JFK
    - JMK
    - JNB
    - JRO
    - JTR
    - KBP
    - KEF
    - KGL
    - KGS
    - KIX
    - KLX
    - KRK
    - KRS
    - KTW
    - KUL
    - KWI
    - LAS
    - LAX
    - LBA
    - LCA
    - LCY
    - LED
    - LHR
    - LIM
    - LIN
    - LIR
    - LIS
    - LJU
    - LOS
    - LPA
    - LPI
    - LUX
    - LYS
    - MAD
    - MAH
    - MAN
    - MCO
    - MCT
    - MEX
    - MIA
    - MLA
    - MME
    - MNL
    - MPL
    - MRS
    - MSP
    - MUC
    - MXP
    - NAP
    - NBO
    - NCE
    - NCL
    - NRT
    - NTE
    - NUE
    - NWI
    - OLB
    - OPO
    - ORD
    - ORK
    - ORY
    - OSL
    - OTP
    - PBM
    - PDX
    - PEK
    - PFO
    - PKX
    - PMI
    - POS
    - POZ
    - PRG
    - PSA
    - PTY
    - PVG
    - PVK
    - RAK
    - RHO
    - RIX
    - RNS
    - RUH
    - RVN
    - SCL
    - SEA
    - SFO
    - SIN
    - SJO
    - SKG
    - SLC
    - SMI
    - SOU
    - SPC
    - SPU
    - SSH
    - STR
    - SVG
    - SVO
    - SVQ
    - SXM
    - SZG
    - TBS
    - TFS
    - TLS
    - TLV
    - TOS
    - TPE
    - TRD
    - TRF
    - TRN
    - UIO
    - VCE
    - VCP
    - VIE
    - VLC
    - VRN
    - WAW
    - WRO
    - XMN
    - YEG
    - YUL
    - YVR
    - YYC
    - YYZ
    - ZAG
    - ZNZ
    - ZRH
    - ZTH
